<a href="https://colab.research.google.com/github/wldus123/PythonStudy/blob/main/IOT2%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

list_python = [9,3,-7.9]
#for n in list_python:
 # print[n]

array_numpy = np.array([9,3,-7.9])
print(list_python)
print(array_numpy)

[9, 3, -7.9]
[ 9.   3.  -7.9]


In [ ]:
a1 = np.zeros((3,2))
a2 = np.ones((2,3,5))
a3 = np.arange(5,15,3)
a4 = np.linspace(0,1,5)

print(array_numpy.shape,array_numpy.ndim, array_numpy.dtype)
print(a1,a1.shape, a1.ndim, a1.dtype)
print(a2,a2.shape,a2.ndim, a2.dtype)
print(a3,a3.dtype)
print(a4)

(3,) 1 float64
[[0. 0.]
 [0. 0.]
 [0. 0.]] (3, 2) 2 float64
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] (2, 3, 5) 3 float64
[ 5  8 11 14] int64
[0.   0.25 0.5  0.75 1.  ]


In [ ]:

# 넘파이 배열 인덱싱 & 슬라이싱

a2[1, 0, 3] = 3.7
a2[0, 2, 1] = 9.1
print(a2)

In [ ]:
print(a4)
print(a4[1:4])
a1[0, 0] = 3
a1[2, 1] = 4
a1[1, 3] = 1
print(a1)
print(a1[1:,1:])
print(a1[:,1:3])
print(a1[:,[0, 3]])

In [ ]:

print(a1)

# 2차원 배열 각 원소에 3을 곱한다. 넘파이 스타일
a1 = a1 * 3
print(a1)

# 2차원 배열 각 원소에 3을 곱한다. 일반 파이썬 반복문 스타일
for i in range(3):
  for j in range(4):
    a1[i, j] = a1[i, j] * 3
print(a1)

In [ ]:

a5 = np.array([[3, 1, 2], [11, -9, 7]])
a6 = np.array([[2, 3, 6], [1, 9, 71]])
print(a5)
print(a6)
# print(a5 + a6)
a7 = a5 + a6
print(a7)
# 2차원 배열 원소중 9보다 작은 값을 1차원 배열로 만든다. 넘파이 스타일
print(a7[a7 < 9])

# 2차원 배열 원소중 9보다 작은 값을 1차원 배열로 만든다. 일반 파이썬 반복문 스타일
# temp = []
# for i in range(2):
#   for j in range(3):
#     if a7[i, j] < 9:
#       temp.append(int(a7[i, j]))
# print(temp)

In [ ]:

print(np.sum(a6))
print(np.min(a6))
print(np.max(a6))
print(np.mean(a6))
print(a6)
print(a6.reshape(3, 2))
print(a6.T)  # 전치행렬


In [ ]:

a8 = np.arange(10, 1, -1)  # 1차원 배열 생성 [10, 9, .... ,3 , 2]
print(a8)
a8 = a8.reshape(3,3)  # 1차원 배열을 2차원 배열로 형태 변환
print(a8)
a8 = a8.T  # 3x3 2차원 배열을 전치행렬로 변환
print(a8)
a8 = a8.flatten()  # 1차원으로 평탄화(펼치기)
print(a8)


In [ ]:

import pandas as pd

subject_dict = {'국':[99, 100, 89, 93], '영':[97, 91, 88, 92], '수':[100, 86, 94, 99]}
# print(subject_dict)
df1 = pd.DataFrame(subject_dict, index=[1, 2, 3, 4])
print(df1)

In [ ]:

subject_2d_list = [
   [99, 97, 100],
   [100, 91, 86],
   [89, 88, 99],
   [93, 92, 99]
]
df2 = pd.DataFrame(subject_2d_list, index=[1, 2, 3, 4], columns=['국','영','수'])
print(df2)

In [ ]:
print(pd.melt(df2).rename(columns={'variable':'var', 'value':'val'}).query('val >= 90'))